import type { Metadata } from "next";
import { Roboto, Open_Sans, Lato } from "next/font/google";
import "./globals.css";
import MiniDrawer from "@/components/layout";
import { DrawerProvider } from "@/providers/drawer";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { cookies } from "next/headers";
import { ThemeProviderComponent } from "@/providers/theme";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });
const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "600"] });
const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Expence Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const session = cookieStore.get("session")?.value;
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${openSans.className} ${lato.className} antialiased`}
      >
        <AppRouterCacheProvider>
          <ThemeProviderComponent>
            <DrawerProvider session={session}>
              <MiniDrawer>{children}</MiniDrawer>
            </DrawerProvider>
          </ThemeProviderComponent>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
