export const countryPhoneCodes = [
  { country: "Türkiye", code: "+90" },
  { country: "ABD", code: "+1" },
  { country: "Kanada", code: "+1" },
  { country: "Almanya", code: "+49" },
  { country: "Birleşik Krallık", code: "+44" },
  { country: "Fransa", code: "+33" },
  { country: "İtalya", code: "+39" },
  { country: "İspanya", code: "+34" },
  { country: "Hollanda", code: "+31" },
  { country: "Avustralya", code: "+61" },
  { country: "Brezilya", code: "+55" },
  { country: "Hindistan", code: "+91" },
  { country: "Çin", code: "+86" },
  { country: "Rusya", code: "+7" },
  { country: "Japonya", code: "+81" },
  { country: "Meksika", code: "+52" },
  { country: "İsveç", code: "+46" },
  { country: "Norveç", code: "+47" },
  { country: "Danimarka", code: "+45" },
  { country: "İsviçre", code: "+41" },
  { country: "Belçika", code: "+32" },
  { country: "Yunanistan", code: "+30" },
  { country: "Portekiz", code: "+351" },
  { country: "Polonya", code: "+48" },
  { country: "Güney Kore", code: "+82" },
  { country: "Suudi Arabistan", code: "+966" },
  { country: "Birleşik Arap Emirlikleri", code: "+971" },
  { country: "Katar", code: "+974" },
  { country: "Mısır", code: "+20" },
  { country: "Güney Afrika", code: "+27" },
];
